name: Upstream latest image

on:
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      tag: latest
      memos_image_tag: latest