name: Upstream stable image with memogram

on:
  push:
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      tag: stable-memogram
      use_memogram: true
      add_version_tag: true