name: Upstream testing

on:
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      tag: test
      platforms: linux/amd64
      pinned_buildx_version: v0.9.1